# Generated by Django 4.0.4 on 2022-07-26 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=100)),
                ('op1', models.CharField(default=False, max_length=100)),
                ('op2', models.CharField(default=False, max_length=100)),
                ('op3', models.CharField(default=False, max_length=100)),
                ('op4', models.CharField(default=False, max_length=100)),
                ('ans', models.CharField(default=False, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=25, unique=True)),
                ('password', models.CharField(max_length=25)),
                ('result', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
